# MateChat Services Deployment Configuration
# 無人機/自動駕駛系統 AI 服務部署配置

apiVersion: v1
kind: DeploymentManifest
metadata:
  name: matechat-drone-services
  version: "1.0.0"
  description: "AI chat services for drone and autonomous vehicle operations"
  tags:
    - ai
    - chat
    - drone
    - autonomous
  governance:
    slsa_level: 3
    security_scan: required
    approval_required: true

# Service Definitions
services:
  - name: ai-chat-service
    type: microservice
    path: core/contracts/contracts-L1/ai-chat-service
    language: typescript
    framework: express
    
    deployment:
      replicas: 3
      strategy: rolling-update
      max_surge: 1
      max_unavailable: 0
      
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"
    
    ports:
      - name: http
        port: 8100
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
    
    health_checks:
      liveness:
        path: /health/live
        interval: 30s
        timeout: 5s
        failure_threshold: 3
      
      readiness:
        path: /health/ready
        interval: 10s
        timeout: 5s
        failure_threshold: 3
      
      startup:
        path: /health
        interval: 10s
        timeout: 5s
        failure_threshold: 30
    
    environment:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8100"
      - name: LOG_LEVEL
        value: info
      - name: OPENAI_API_KEY
        valueFrom:
          secretRef:
            name: openai-credentials
            key: api-key
      - name: AI_MODEL
        value: gpt-4-turbo-preview
      - name: MAX_TOKENS
        value: "4096"
      - name: TEMPERATURE
        value: "0.7"
    
    security:
      run_as_non_root: true
      read_only_root_filesystem: true
      allow_privilege_escalation: false
      capabilities:
        drop:
          - ALL
      
      network_policies:
        - name: allow-ingress
          ingress:
            - from:
                - podSelector:
                    matchLabels:
                      app: drone-control
              ports:
                - protocol: TCP
                  port: 8100
        
        - name: allow-egress
          egress:
            - to:
                - podSelector:
                    matchLabels:
                      app: openai-api
              ports:
                - protocol: TCP
                  port: 443

  - name: input-service
    type: microservice
    path: core/contracts/contracts-L1/input-service
    status: planned
    dependencies:
      - ai-chat-service
    
  - name: file-service
    type: microservice
    path: core/contracts/contracts-L1/file-service
    status: planned
    dependencies:
      - ai-chat-service

  - name: markdown-renderer
    type: library
    path: advanced-system-src/markdown-renderer
    status: planned
    
  - name: ai-model-integration
    type: mcp-server
    path: mcp-servers/ai-model-integration
    status: planned

# Integration Configuration
integrations:
  - name: openai-api
    type: external
    endpoint: https://api.openai.com/v1
    authentication: api-key
    rate_limits:
      requests_per_minute: 60
      tokens_per_minute: 150000
  
  - name: drone-control-system
    type: internal
    endpoint: http://drone-control:8000
    authentication: jwt
  
  - name: telemetry-collector
    type: internal
    endpoint: http://telemetry:8080
    authentication: mutual-tls

# Monitoring Configuration
monitoring:
  enabled: true
  
  metrics:
    - name: request_duration_ms
      type: histogram
      labels: [method, endpoint, status]
    
    - name: active_connections
      type: gauge
      labels: [service]
    
    - name: ai_tokens_used
      type: counter
      labels: [model, user]
    
    - name: error_rate
      type: counter
      labels: [error_type, service]
  
  alerts:
    - name: HighLatency
      condition: request_duration_ms > 2000
      severity: warning
      notification:
        - slack
        - email
    
    - name: ServiceDown
      condition: health_check_failures > 3
      severity: critical
      notification:
        - pagerduty
        - slack
    
    - name: HighErrorRate
      condition: error_rate > 0.05
      severity: warning
      notification:
        - slack

# Rollout Strategy
rollout:
  phases:
    - name: canary
      percentage: 10
      duration: 1h
      success_criteria:
        - error_rate < 0.01
        - latency_p95 < 2000ms
    
    - name: staged
      percentage: 50
      duration: 2h
      success_criteria:
        - error_rate < 0.01
        - latency_p95 < 2000ms
    
    - name: full
      percentage: 100
      duration: ongoing

# Backup and Recovery
backup:
  enabled: true
  schedule: "0 */6 * * *"  # Every 6 hours
  retention_days: 30
  
  targets:
    - logs
    - configuration
    - telemetry_data

recovery:
  rto: 15m  # Recovery Time Objective
  rpo: 1h   # Recovery Point Objective
  
  procedures:
    - name: service-restart
      trigger: health_check_failure
      actions:
        - restart_pod
        - notify_oncall
    
    - name: rollback
      trigger: high_error_rate
      actions:
        - revert_to_previous_version
        - notify_team
        - create_incident

# Compliance and Governance
compliance:
  slsa:
    level: 3
    requirements:
      - source_integrity
      - build_service
      - provenance
      - non_falsifiable
  
  security_scanning:
    - sast: required
    - dast: required
    - dependency_check: required
    - container_scan: required
  
  audit_logging:
    enabled: true
    retention_days: 365
    log_types:
      - api_requests
      - configuration_changes
      - authentication_events
      - authorization_decisions

# Documentation
documentation:
  readme: core/contracts/contracts-L1/ai-chat-service/README.md
  api_spec: core/contracts/contracts-L1/ai-chat-service/openapi.yml
  architecture: docs/architecture/ai-chat-service.md
  runbook: docs/runbooks/ai-chat-service-operations.md
