# Organization Security Policy
# Enterprise-level security configuration for GitHub Advanced Security

name: "Organization Security Policy"
description: "Enterprise-level security configuration"

# GitHub Advanced Security configuration
security_and_analysis:
  # Enable GitHub Advanced Security for all repositories
  advanced_security:
    status: enabled
  
  # Enable secret scanning to detect secrets in code
  secret_scanning:
    status: enabled
  
  # Enable push protection to prevent secrets from being committed
  secret_scanning_push_protection:
    status: enabled
  
  # Enable dependency graph to track dependencies
  dependency_graph:
    status: enabled
  
  # Enable Dependabot security updates for automatic security patches
  dependabot_security_updates:
    status: enabled

# Security scanning configuration
security_scanning:
  # CodeQL configuration
  codeql:
    enabled: true
    languages:
      - javascript
      - typescript
      - python
      - java
      - go
      - csharp
    schedule:
      # Run CodeQL analysis on a schedule
      - cron: "0 0 * * 0"  # Weekly on Sunday at midnight
    on_push: true
    on_pull_request: true
  
  # Secret scanning configuration
  secret_scanning:
    enabled: true
    # Block commits containing secrets
    push_protection: true
    # Scan historical commits
    scan_history: true
  
  # Dependency scanning configuration
  dependency_scanning:
    enabled: true
    # Auto-update dependencies with security vulnerabilities
    auto_update: true
    # Severity threshold for alerts
    severity_threshold: "medium"

# Branch protection rules
branch_protection:
  # Protect main branch
  main:
    required_reviews: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    required_status_checks:
      - "ci/build"
      - "ci/test"
      - "security/codeql"
      - "security/dependency-check"
    enforce_admins: true
    require_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
  
  # Protect release branches
  release/*:
    required_reviews: 2
    required_status_checks:
      - "ci/build"
      - "ci/test"
      - "security/codeql"
    enforce_admins: true

# Security policies
security_policies:
  # Vulnerability disclosure policy
  vulnerability_disclosure:
    enabled: true
    contact: "security@example.com"
    
  # Security advisory policy
  security_advisory:
    enabled: true
    auto_publish: false
    
  # Compliance requirements
  compliance:
    - "GDPR"
    - "SOC2"
    - "ISO27001"

# Alert management
alert_management:
  # Auto-dismiss settings
  auto_dismiss:
    # Dismiss alerts older than 90 days if no action taken
    stale_alerts_days: 90
    
  # Notification settings
  notifications:
    # Send notifications to security team
    email:
      - "security-team@example.com"
    slack:
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#security-alerts"
    
  # Alert severity levels
  severity_levels:
    critical:
      notify_immediately: true
      require_acknowledgment: true
    high:
      notify_within_hours: 4
      require_acknowledgment: true
    medium:
      notify_daily_digest: true
    low:
      notify_weekly_digest: true

# Access control
access_control:
  # Team permissions
  teams:
    security-team:
      permission: "admin"
      repositories: "all"
      can_create_repos: true
      can_delete_repos: false
    
    development-team:
      permission: "write"
      repositories: ["dev/*", "staging/*"]
      can_create_repos: true
      can_delete_repos: false
    
    operations-team:
      permission: "read"
      repositories: ["prod/*"]
      can_create_repos: false
      can_delete_repos: false
  
  # Two-factor authentication
  require_2fa: true
  
  # SSO enforcement
  sso:
    enabled: true
    provider: "saml"

# Audit logging
audit_logging:
  enabled: true
  retention_days: 365
  events:
    - "repository.create"
    - "repository.delete"
    - "repository.security_alert"
    - "organization.security_team_change"
    - "organization.member_added"
    - "organization.member_removed"

# Compliance scanning
compliance_scanning:
  enabled: true
  frameworks:
    - "OWASP Top 10"
    - "CWE Top 25"
    - "SANS Top 25"
  
  # Custom rules
  custom_rules:
    enabled: true
    rules_path: ".github/security-rules"

# Integration settings
integrations:
  # SIEM integration
  siem:
    enabled: true
    provider: "elasticsearch"
    endpoint: "${ELASTICSEARCH_ENDPOINT}"
  
  # Ticketing system integration
  ticketing:
    enabled: true
    provider: "jira"
    project_key: "SEC"
    auto_create_tickets: true
    severity_mapping:
      critical: "Highest"
      high: "High"
      medium: "Medium"
      low: "Low"
