---
# ==============================================================================
# Drift Detection CronJob
# ==============================================================================
# ç”¨é€”: å®šæœŸæŽƒæé…ç½®å·®ç•°ä¸¦ç”¢ç”Ÿå ±å‘Š
# èªžè¨€: ç¹é«”ä¸­æ–‡
# ==============================================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: drift-detector
  namespace: platform
  labels:
    app: drift-detector
    component: governance
spec:
  # æ¯15åˆ†é˜åŸ·è¡Œä¸€æ¬¡
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: drift-detector
    spec:
      template:
        metadata:
          labels:
            app: drift-detector
        spec:
          serviceAccountName: drift-detector
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: drift-scanner
            image: drift-detector:latest@sha256:placeholder
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                echo "ðŸ” é–‹å§‹ Drift æŽƒæ..."
                echo "æ™‚é–“: $(date)"
                
                # è¼‰å…¥é…ç½®
                kubectl get configmap drift-rules -n platform -o jsonpath='{.data.rules\.yaml}' > /tmp/rules.yaml
                
                # æŽƒæ Deployments
                echo "æŽƒæ Deployments..."
                kubectl get deployments --all-namespaces -o yaml > /tmp/current-deployments.yaml
                
                # å¾ž Git å–å¾—æœŸæœ›é…ç½®
                if [ -d "/config" ]; then
                  echo "æ¯”å° Git é…ç½®..."
                  # é€™è£¡æ‡‰è©²æ¯”å° /config èˆ‡å¯¦éš›é…ç½®çš„å·®ç•°
                fi
                
                # ç”Ÿæˆå ±å‘Š
                REPORT_FILE="drift-report-$(date +%Y%m%d-%H%M%S).json"
                cat > "/reports/$REPORT_FILE" << EOF
                {
                  "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
                  "scan_duration": "5s",
                  "total_resources_scanned": 0,
                  "drifts_detected": 0,
                  "violations": []
                }
                EOF
                
                echo "âœ… Drift æŽƒæå®Œæˆ"
                echo "å ±å‘Š: $REPORT_FILE"
            env:
            - name: KUBECONFIG
              value: /var/run/secrets/kubernetes.io/serviceaccount
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
            - name: reports
              mountPath: /reports
            - name: config
              mountPath: /config
              readOnly: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
          volumes:
          - name: reports
            emptyDir: {}
          - name: config
            configMap:
              name: drift-rules
              optional: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drift-detector
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drift-detector
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drift-detector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drift-detector
subjects:
- kind: ServiceAccount
  name: drift-detector
  namespace: platform

# ==============================================================================
# ä½¿ç”¨èªªæ˜Ž
# ==============================================================================
# éƒ¨ç½²:
#   kubectl apply -f drift/scan-cronjob.yaml
#
# æ‰‹å‹•è§¸ç™¼:
#   kubectl create job drift-scan-manual --from=cronjob/drift-detector -n platform
#
# æŸ¥çœ‹æ—¥èªŒ:
#   kubectl logs -l app=drift-detector -n platform
#
# æŸ¥çœ‹å ±å‘Š:
#   kubectl exec -it $(kubectl get pods -l app=drift-detector -n platform -o name | head -1) -- cat /reports/drift-report-*.json
# ==============================================================================
