---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GeoFencePolicy
metadata:
  name: geo-fence-policy
  annotations:
    description: "Enforce geo-fencing configuration for UAV systems"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
    labelSelector:
      matchLabels:
        uav.io/system: "uav"
  parameters:
    message: "UAV ConfigMap must include valid geo-fencing configuration"
    geoFenceEnabled: true
    geoFenceRegions:
      - "TW-North"
      - "JP-Tokyo"
