---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: uav-ad-required-labels
  annotations:
    description: >-
      Ensure UAV/AD resources have required labels for
      governance and traceability
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace", "ConfigMap", "Service"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
  parameters:
    message: "Resources must include required labels for UAV/AD governance"
    labels:
      # Standard namespace labels
      - key: "namespace.io/managed-by"
        allowedRegex: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
      - key: "namespace.io/domain"
        allowedRegex: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
      - key: "namespace.io/environment"
        allowedRegex: "^(dev|development|staging|production|prod)$"
      - key: "namespace.io/lifecycle"
        allowedRegex: "^(experimental|stable|deprecated)$"
      # UAV/AD specific labels for Deployments
      - key: "uav.io/system"
        allowedRegex: "^(uav|ad)$"
        # 原本僅限 Deployment/StatefulSet/DaemonSet，建議拆分約束於 spec.match 層級過濾
      - key: "uav.io/safety-level"
        allowedRegex: "^L[0-5]$"
        # 原本僅限 Deployment/StatefulSet/DaemonSet，建議拆分約束於 spec.match 層級過濾
