---
# UAV Production Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: uav-production
  labels:
    namespace.io/managed-by: "platform-team"
    namespace.io/domain: "uav"
    namespace.io/team: "robotics"
    namespace.io/environment: "production"
    namespace.io/region: "asia-east1"
    namespace.io/lifecycle: "stable"
    uav.io/system: "uav"
  annotations:
    description: "Production environment for UAV systems"
---
# Autonomous Driving Production Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ad-production
  labels:
    namespace.io/managed-by: "platform-team"
    namespace.io/domain: "ad"
    namespace.io/team: "autonomous-vehicles"
    namespace.io/environment: "production"
    namespace.io/region: "asia-east1"
    namespace.io/lifecycle: "stable"
    uav.io/system: "ad"
  annotations:
    description: "Production environment for autonomous driving systems"
